name: Java CI with Maven

on:
  pull_request:
    branches:
      - main 
  push:
    branches; 
      -main

jobs:
  test:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: '22' 

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository 
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}  
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn install -DskipTests=true  

      - name: Run tests with Maven
        run: mvn test  
